function BER = runSDRuQPSKReceiver(prmQPSKReceiver, printData)

    %#codegen
    persistent qpskRx radio

    if isempty(qpskRx)
        qpskRx = QPSKReceiver(...
            'ModulationOrder', prmQPSKReceiver.ModulationOrder, ...
            'SampleRate', prmQPSKReceiver.Fs, ...
            'DecimationFactor', prmQPSKReceiver.Decimation, ...
            'FrameSize', prmQPSKReceiver.FrameSize, ...
            'HeaderLength', prmQPSKReceiver.HeaderLength, ...
            'NumberOfMessage', prmQPSKReceiver.NumberOfMessage, ...
            'PayloadLength', prmQPSKReceiver.PayloadLength, ...
            'DesiredPower', prmQPSKReceiver.DesiredPower, ...
            'AveragingLength', prmQPSKReceiver.AveragingLength, ...
            'MaxPowerGain', prmQPSKReceiver.MaxPowerGain, ...
            'RolloffFactor', prmQPSKReceiver.RolloffFactor, ...
            'RaisedCosineFilterSpan', prmQPSKReceiver.RaisedCosineFilterSpan, ...
            'InputSamplesPerSymbol', prmQPSKReceiver.Interpolation, ...
            'MaximumFrequencyOffset', prmQPSKReceiver.MaximumFrequencyOffset, ...
            'PostFilterOversampling', prmQPSKReceiver.Interpolation / prmQPSKReceiver.Decimation, ...
            'PhaseRecoveryLoopBandwidth', prmQPSKReceiver.PhaseRecoveryLoopBandwidth, ...
            'PhaseRecoveryDampingFactor', prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
            'TimingRecoveryDampingFactor', prmQPSKReceiver.TimingRecoveryDampingFactor, ...
            'TimingRecoveryLoopBandwidth', prmQPSKReceiver.TimingRecoveryLoopBandwidth, ...
            'TimingErrorDetectorGain', prmQPSKReceiver.TimingErrorDetectorGain, ...
            'PreambleDetectorThreshold', prmQPSKReceiver.PreambleDetectorThreshold, ...
            'DescramblerBase', prmQPSKReceiver.ScramblerBase, ...
            'DescramblerPolynomial', prmQPSKReceiver.ScramblerPolynomial, ...
            'DescramblerInitialConditions', prmQPSKReceiver.ScramblerInitialConditions, ...
            'BerMask', prmQPSKReceiver.BerMask, ...
            'InterweaveDepth', prmQPSKReceiver.InterweaveDepth, ...
            'InterweaveLength', prmQPSKReceiver.InterweaveLength, ...
            'PrintOption', printData);

        % Create and configure the SDRu System object. Set the SerialNum for B2xx
        % radios and IPAddress for X3xx, N2xx, N3xx, and USRP2 radios. MasterClockRate
        % is not configurable for N2xx and USRP2 radios.
        %{

        switch prmQPSKReceiver.Platform
            case {'B200', 'B210'}
                radio = comm.SDRuReceiver(...
                    'Platform', prmQPSKReceiver.Platform, ...
                    'SerialNum', prmQPSKReceiver.Address, ...
                    'MasterClockRate', prmQPSKReceiver.MasterClockRate, ...
                    'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
                    'Gain', prmQPSKReceiver.USRPGain, ...
                    'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
                    'SamplesPerFrame', prmQPSKReceiver.USRPFrameLength, ...
                    'OutputDataType', 'double');
            case {'X300', 'X310'}
                radio = comm.SDRuReceiver(...
                    'Platform', prmQPSKReceiver.Platform, ...
                    'IPAddress', prmQPSKReceiver.Address, ...
                    'MasterClockRate', prmQPSKReceiver.MasterClockRate, ...
                    'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
                    'Gain', prmQPSKReceiver.USRPGain, ...
                    'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
                    'SamplesPerFrame', prmQPSKReceiver.USRPFrameLength, ...
                    'OutputDataType', 'double');
            case {'N200/N210/USRP2'}
                radio = comm.SDRuReceiver(...
                    'Platform', prmQPSKReceiver.Platform, ...
                    'IPAddress', prmQPSKReceiver.Address, ...
                    'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
                    'Gain', prmQPSKReceiver.USRPGain, ...
                    'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
                    'SamplesPerFrame', prmQPSKReceiver.USRPFrameLength, ...
                    'OutputDataType', 'double');
            case {'N300', 'N310'}
                radio = comm.SDRuReceiver(...
                    'Platform', prmQPSKReceiver.Platform, ...
                    'IPAddress', prmQPSKReceiver.Address, ...
                    'MasterClockRate', prmQPSKReceiver.MasterClockRate, ...
                    'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
                    'Gain', prmQPSKReceiver.USRPGain, ...
                    'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
                    'SamplesPerFrame', prmQPSKReceiver.USRPFrameLength, ...
                    'OutputDataType', 'double');
            case {'N320/N321'}
                radio = comm.SDRuReceiver(...
                    'Platform', prmQPSKReceiver.Platform, ...
                    'IPAddress', prmQPSKReceiver.Address, ...
                    'MasterClockRate', prmQPSKReceiver.MasterClockRate, ...
                    'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
                    'Gain', prmQPSKReceiver.USRPGain, ...
                    'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
                    'SamplesPerFrame', prmQPSKReceiver.USRPFrameLength, ...
                    'OutputDataType', 'double');
        end

        %}

        radio = comm.SDRuReceiver(...
            'Platform', prmQPSKReceiver.Platform, ...
            'IPAddress', prmQPSKReceiver.Address, ...
            'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
            'Gain', prmQPSKReceiver.USRPGain, ...
            'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
            'SamplesPerFrame', prmQPSKReceiver.USRPFrameLength, ...
            'OutputDataType', 'double');

    end

    disp('start')

    % Initialize variables
    len = uint32(0);
    rcvdSignal = complex(zeros(prmQPSKReceiver.USRPFrameLength, 1));
    BER = [];
    currentTime = 0;

    timestep = 2;
    d = clock;
    fcIdx = max(ceil(d(6) / timestep), 1);
    flag = mod(fcIdx * timestep, 60);
    radio.CenterFrequency = prmQPSKReceiver.Fcs(fcIdx);

    rev = zeros(10000000);
    idx = 1;

    paused = false;

    while currentTime < prmQPSKReceiver.StopTime
        % Keep accessing the SDRu System object output until it is valid
        while len <= 0
            [rcvdSignal, len] = step(radio);
        end

        d = clock;

        if paused && d(6) > flag
            flag = flag + timestep - 0.2;
            paused = false;
            continue
        end

        % When the SDRu System object output is valid, decode the received
        % message
        if len > 0
            [~, ~, ~, BER, msg] = qpskRx(rcvdSignal); % Receiver
            l = length(msg);
            rev(idx:idx + l) = msg;
            idx = idx + l;
        end

        len = uint32(0);
        currentTime = currentTime + prmQPSKReceiver.USRPFrameTime;

        % TODO position

        if d(6) > flag
            flag = flag + 0.2;

            if flag >= 60
                flag = 0;
                fcIdx = 1;
            else
                fcIdx = fcIdx + 1;
            end

            radio.CenterFrequency = prmQPSKTransmitter.Fcs(fcIdx);
            paused = true;
        end

        %{

        if d(6) > flag
            flag = flag + timestep;

            if flag >= 60
                flag = timestep;
                fcIdx = 1;
            else
                fcIdx = fcIdx + 1;
            end

            radio.CenterFrequency = prmQPSKTransmitter.Fcs(fcIdx);
        end

        %}
    end

    save('test.mat', 'rev', '-v7.3')

    release(qpskRx);
    release(radio);

end
